### ISSUE TITLE
Odd number of elements in hash assignment at /usr/local/share/perl/5.30.0/Binance/API.pm line 671

### ISSUE THREAD

**Issue by baloo98** [taskula/binance-perl-api#12]
Hi Lari,

Happy new year.

I take some time to finish my code with your Binance::API.

So now when I ask $api->ticker_price like this
my $paire=$mycoin->{"asset"}."USDT";
@coursbinance= $api->ticker_price($paire);

I receive this message in the syslog : "Odd number of elements in hash assignment at /usr/local/share/perl/5.30.0/Binance/API.pm line 671"

Do you know why, and where is my error ?

Regard,
Marc

**Comment by taskula** [comment]
The method takes a hash as a parameter, not a scalar. You need to use:

$api->ticker_price( symbol => $paire );

Happy new year!

**Comment by baloo98** [comment]
Hi Lary,

I need to go to quicly to test sell market order with your API, but it
still in my to do.

As all is now in USDT, why the $api->account() [that give me my spot
position correctly] dont give me the USDT quantity ?
On binance I can see them at the top of the list.

Regards,
Marc

Le sam. 2 janv. 2021 à 13:38, Lari Taskula <notifications@github.com> a
écrit :

> The method takes a hash as a parameter, not a scalar. You need to use:
>
> $api->ticker_price( symbol => $paire );
>
> Happy new year!
>

**Comment by baloo98** [comment]
Sorry it's a mistake from me.


Le mar. 12 janv. 2021 à 15:27, Marc Travaillé <marc.travaille@gmail.com> a
écrit :

> Hi Lary,
>
> I need to go to quicly to test sell market order with your API, but it
> still in my to do.
>
> As all is now in USDT, why the $api->account() [that give me my spot
> position correctly] dont give me the USDT quantity ?
> On binance I can see them at the top of the list.
>
> Regards,
> Marc
>
> Le sam. 2 janv. 2021 à 13:38, Lari Taskula <notifications@github.com> a
> écrit :
>
>> The method takes a hash as a parameter, not a scalar. You need to use:
>>
>> $api->ticker_price( symbol => $paire );
>>
>> Happy new year!
>>

**Comment by baloo98** [comment]
Hi Lary,

I'm back after Market order test, and I have an error.

when I call the API with:
$retAPI=$api->order(
   symbol => 'BTCUSDT',
   side   => 'BUY',
   type   => 'MARKET',
       timeInForce => 'GTC',
   price =>5000
);

[Binance::API::order] Parameter "quantity" required at
/usr/local/share/perl/5.30.0/Binance/API.pm line 834.

Where am I wrong please ?

Regards,
Marc

Le mar. 12 janv. 2021 à 15:32, Marc Travaillé <marc.travaille@gmail.com> a
écrit :

> Sorry it's a mistake from me.
>
>
> Le mar. 12 janv. 2021 à 15:27, Marc Travaillé <marc.travaille@gmail.com>
> a écrit :
>
>> Hi Lary,
>>
>> I need to go to quicly to test sell market order with your API, but it
>> still in my to do.
>>
>> As all is now in USDT, why the $api->account() [that give me my spot
>> position correctly] dont give me the USDT quantity ?
>> On binance I can see them at the top of the list.
>>
>> Regards,
>> Marc
>>
>> Le sam. 2 janv. 2021 à 13:38, Lari Taskula <notifications@github.com> a
>> écrit :
>>
>>> The method takes a hash as a parameter, not a scalar. You need to use:
>>>
>>> $api->ticker_price( symbol => $paire );
>>>
>>> Happy new year!
>>>

**Comment by baloo98** [comment]
It work fine, thank's
