### ISSUE TITLE
Unitialized warning from UserAgent.pm line 300

### ISSUE THREAD

**Issue by oldcoder47** [taskula/binance-perl-api#18]
$self->{max_redirect} is not defined, so I get a warning message and also a premature return happens.
max_redirect must be set to 1, not 0.
See this:
https://www.perlmonks.org/?node_id=1210840#:~:text=%22Redirect%20loop%20detection,will%20be%20run.%22
I made this change to my copy of UserAgent.pm at line 299:
if (!defined($self->{max_redirect})) {$self->{max_redirect} = 1;} 
Everything seems to work OK.
This is not the best solution - you should correct Binance::API

**Comment by taskula** [comment]
For some reason I do not get the warning. But your issue revealed that we had not initialized LWP::UserAgent by calling its constructor in Binance::API::Request->new. Thanks for reporting this. Should be resolved by 726f9fd.
