### ISSUE TITLE
Signature generation

### ISSUE THREAD

**Issue by taskula** [taskula/binance-perl-api#3]
`{"code":-1022,"msg":"Signature for this request is not valid."}`

**Comment by xFFFFF** [comment]
I tried, without success. I'm letting go today. From what some have written, the timestamp must be as the last but one, and signature as the last parameter. Some of them helped recvWindow = 6000. Unfortunately, it did not help me. Have you tried this query by the Linux curl? I have not been able to formulate any correct query, maybe I am doing something wrong. Maybe we could try to run a call system with a generated link instead of LWP to check if the signature is wrong?

**Comment by xFFFFF** [comment]
WORK! Yesterday I guess I was too sleepy as I played with it. It was enough to add recvWindow
`my $ticker = $api->allOrders( symbol => 'TRXBTC', recvWindow=> 6000 );`

**Comment by xFFFFF** [comment]
```
my $api = Binance::API->new(
    apiKey    => 'x',
    secretKey => 'y',
    logger => 'error'
);

my $ticker = $api->allOrders( symbol => 'TRXBTC', recvWindow=> 60000000, limit => 1 );
```
request.pm
```
    elsif (keys %$query || !keys %$query && !keys %$body) {
        $query->{'timestamp'} = $timestamp;
        if (!defined $query->{'recvWindow'} && defined $recvWindow) {
            $query->{'recvWindow'} = $recvWindow;
        }
        $uri->query_form($query);
        if ($params->{signed}) {
           $query->{signature} = hmac_sha256_hex( $uri->query, $self->{secretKey}  );
            $uri->query_form( {
              symbol => $query->{'symbol'},
              recvWindow => $query->{'recvWindow'},
              limit => $query->{'limit'},
              timestamp => $query->{'timestamp'},
              signature => $query->{'signature'}
            });
        $full_path = $uri->as_string;
      }
    }
```

**Comment by taskula** [comment]
I figured out 7510e0a fixed this, but it was an incomplete fix. The real issue was that recvWindow was not passed from Binance::API->new( recvWindow => 12345 ) into Binance::API::Request.

This is now fixed in 06fa14d6b2a62f8e42d290a9844221cbc5d5df12. Also added tests for that.

**Comment by xFFFFF** [comment]
I added recvWindow as one of the parameters to call `$api->allOrders()`. Not all requests to API need recvWindow...

**Comment by taskula** [comment]
Yep, only the signed requests can optionally have the parameter. This is included in the commit. You can instantiate Binance::API with recvWindow of 10000, and it will apply only for the signed requests.

Additionally you should still be able to define it for individual calls to the API, like you did before.
