### ISSUE TITLE
send Market order

### ISSUE THREAD

**Issue by baloo98** [taskula/binance-perl-api#9]
Hi,

In binance documentation, for a MARKET order, we need symbol, side, type and quantity or quoteorderQty for them, (price for you.)

I have an error with MARKET type order, because (I think) all LIMIT type parameter are required.

How can I do to send Market order please ?

Regards,

**Comment by taskula** [comment]
Hi, welcome to the project and thanks for reporting the issue.

You are correct. Depending on the `type` parameter, some of the other parameters become required. [1]

I'm not sure why we are missing that. If Binance has added parameter requirements after this module was first released (Dec 2017), it is possible that some methods are now broken. But I don't know how Binance manages API updates so I'm just guessing.

I'll update the parameters and their requirements.

[1] https://github.com/binance-exchange/binance-official-api-docs/blob/7a8d958157d3c0ed8ddaead8d1c0273ec9a3504e/rest-api.md#new-order--trade

**Comment by taskula** [comment]
Can you test if https://github.com/taskula/binance-perl-api/commit/2401f9b1430e782f314d2c755577138c2c1332e5 works?

**Comment by taskula** [comment]
Issue author reported that they are unable to contribute further. I'll test it myself and merge https://github.com/taskula/binance-perl-api/tree/issue_9 to master.

Closing issue.

Edit: Fixed by 6c6ab8fcda5e3430b5cc1ae5fc8f348763c83f76

**Comment by baloo98** [comment]
Hi Lari

I test the upgrade realese for market Order;
For BUY MARKET test using $api->order_test(
I test with quoteOrderQty parameter, and it's look like your are only waiting quantity parameter for market order.
So I test with quantity parameter and it look like now waiting Price but it's not require for market order if I understand Binance doc.
For SELL MARKET order, it is the same error.

Adding price give a new error
[Binance::API::Request::_exec] Bad Request at /usr/local/share/perl/5.30.0/Binance/API/Request.pm line 105.

How need I do ?

regards
